import type { Game } from "./types";

export const games: Game[] = [
  {
    id: "stardew-valley",
    name: "Stardew Valley",
    image: "/covers/stardew-valley.svg",
    genres: ["Farming", "RPG", "Simulation"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 4,
    coopOnline: true,
    coopLocal: true,
  },
  {
    id: "minecraft",
    name: "Minecraft",
    image: "/covers/minecraft.svg",
    genres: ["Survival", "Building"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 8,
    coopOnline: true,
    coopLocal: true,
  },
  {
    id: "terraria",
    name: "Terraria",
    image: "/covers/terraria.svg",
    genres: ["Survival", "Building", "RPG"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 8,
    coopOnline: true,
    coopLocal: true,
  },
  {
    id: "valheim",
    name: "Valheim",
    image: "/covers/valheim.svg",
    genres: ["Survival", "Building"],
    platforms: ["Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 10,
    coopOnline: true,
    coopLocal: false,
  },
  {
    id: "overcooked-2",
    name: "Overcooked! 2",
    image: "/covers/overcooked-2.svg",
    genres: ["Simulation"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 4,
    coopOnline: true,
    coopLocal: true,
  },
  {
    id: "dont-starve-together",
    name: "Don't Starve Together",
    image: "/covers/dont-starve-together.svg",
    genres: ["Survival"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 6,
    coopOnline: true,
    coopLocal: false,
  },
  {
    id: "factorio",
    name: "Factorio",
    image: "/covers/factorio.svg",
    genres: ["Building", "Simulation"],
    platforms: ["Mac", "Windows", "Linux"],
    minPlayers: 1,
    maxPlayers: 8,
    coopOnline: true,
    coopLocal: false,
  },
  {
    id: "it-takes-two",
    name: "It Takes Two",
    image: "/covers/it-takes-two.svg",
    genres: ["RPG"],
    platforms: ["Mac", "Windows"],
    minPlayers: 2,
    maxPlayers: 2,
    coopOnline: true,
    coopLocal: true,
  },
];
